# Generated by Django 5.0.6 on 2024-09-02 12:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
