# Generated by Django 5.0.6 on 2024-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_managers_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa'},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=180, verbose_name='Descrição detalhada da tarefa'),
        ),
    ]
